# Generated by Django 5.0.2 on 2024-03-04 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationModel',
            fields=[
                ('nation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nation_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nation_table',
            },
        ),
        migrations.CreateModel(
            name='NationImageModel',
            fields=[
                ('nation_image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nation_image', models.ImageField(upload_to='nation/')),
                ('nation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.nationmodel')),
            ],
            options={
                'db_table': 'nation_image',
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('Nation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.nationmodel')),
            ],
            options={
                'db_table': 'city_table',
            },
        ),
        migrations.CreateModel(
            name='PackagesModel',
            fields=[
                ('packages_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('package_name', models.CharField(max_length=255)),
                ('no_of_bookings', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('package_image', models.ImageField(upload_to='packages/')),
                ('description', models.CharField(max_length=255)),
                ('nation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.nationmodel')),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='PackagePlanModel',
            fields=[
                ('plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('oder', models.IntegerField()),
                ('no_of_days', models.IntegerField()),
                ('activity', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packagesmodel')),
            ],
            options={
                'db_table': 'package_plan',
            },
        ),
        migrations.CreateModel(
            name='TravelTipsModel',
            fields=[
                ('tips_id', models.IntegerField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
                ('clothing', models.CharField(max_length=255)),
                ('food', models.CharField(max_length=255)),
                ('public_transport', models.CharField(max_length=255)),
                ('shopping', models.CharField(max_length=255)),
                ('nation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.nationmodel')),
            ],
            options={
                'db_table': 'travel_tips',
            },
        ),
    ]
