# Generated by Django 5.0.2 on 2024-03-05 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_delete_citymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDateModel',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packagesmodel')),
            ],
        ),
    ]
