# Generated by Django 5.0.2 on 2024-03-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_packagedatemodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packagedatemodel',
            table='packagedate',
        ),
    ]
