# Generated by Django 5.0.2 on 2024-03-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_packagedatemodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationmodel',
            name='nation_description',
            field=models.TextField(null=True),
        ),
    ]
