# Generated by Django 5.0.2 on 2024-03-08 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_nationmodel_nation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePageModel',
            fields=[
                ('page_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nation_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='packagepage/')),
                ('nation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.nationmodel')),
            ],
            options={
                'db_table': 'package_page_images',
            },
        ),
    ]
