# Generated by Django 5.0.2 on 2024-03-08 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_packagepagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoutryContentsModel',
            fields=[
                ('contents_model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('travel_tip_main_image', models.ImageField(upload_to='countrycontent')),
                ('package_main_image', models.ImageField(upload_to='countrycontent')),
                ('nation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.nationmodel')),
            ],
        ),
    ]
