# Generated by Django 5.0.2 on 2024-03-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_coutrycontentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationimagemodel',
            name='package_main_image',
            field=models.ImageField(null=True, upload_to='countrycontent'),
        ),
        migrations.AddField(
            model_name='nationimagemodel',
            name='travel_tip_main_image',
            field=models.ImageField(null=True, upload_to='countrycontent'),
        ),
        migrations.DeleteModel(
            name='CoutryContentsModel',
        ),
    ]
