# Generated by Django 5.0.2 on 2024-03-08 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_nationimagemodel_package_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepagemodel',
            name='packages_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.packagesmodel'),
        ),
    ]
