# Generated by Django 5.0.2 on 2024-03-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_packagepagemodel_packages_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagepagemodel',
            name='packages_id',
        ),
    ]
