# Generated by Django 5.0.2 on 2024-03-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_remove_packagepagemodel_packages_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysActivityModel',
            fields=[
                ('days_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day1_activity', models.CharField(max_length=255)),
                ('day2_activity', models.CharField(max_length=255)),
                ('day3_activity', models.CharField(max_length=255)),
                ('day4_activity', models.CharField(max_length=255)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packageplanmodel')),
            ],
            options={
                'db_table': 'days_activity',
            },
        ),
    ]
