# Generated by Django 5.0.2 on 2024-03-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_daysactivitymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageplanmodel',
            name='activity',
        ),
    ]
