# Generated by Django 5.0.2 on 2024-03-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_remove_packageplanmodel_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysactivitymodel',
            name='package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.packagesmodel'),
        ),
    ]
