# Generated by Django 5.0.2 on 2024-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_daysactivitymodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltipsmodel',
            name='climate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='traveltipsmodel',
            name='clothing',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='traveltipsmodel',
            name='currency',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='traveltipsmodel',
            name='food',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='traveltipsmodel',
            name='public_transport',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='traveltipsmodel',
            name='shopping',
            field=models.TextField(),
        ),
    ]
