# Generated by Django 5.0.2 on 2024-03-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_alter_traveltipsmodel_climate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaysActivityModel',
        ),
    ]
