# Generated by Django 5.0.2 on 2024-03-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_delete_daysactivitymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplanmodel',
            name='heading',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
