# Generated by Django 5.0.2 on 2024-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_packageplanmodel_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesmodel',
            name='total_days',
            field=models.IntegerField(null=True),
        ),
    ]
