# Generated by Django 5.0.2 on 2024-03-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_packagesmodel_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesmodel',
            name='packages_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
