# Generated by Django 5.0.2 on 2024-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_alter_packagesmodel_packages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesmodel',
            name='packages_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
