# Generated by Django 5.0.2 on 2024-03-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_rename_package_id_packageplanmodel_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveltipsmodel',
            old_name='nation_id',
            new_name='nation',
        ),
    ]
