# Generated by Django 5.0.2 on 2024-04-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_rename_nation_id_traveltipsmodel_nation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedatemodel',
            name='end_date',
        ),
        migrations.AddField(
            model_name='packagedatemodel',
            name='count',
            field=models.IntegerField(default=10),
        ),
    ]
