# Generated by Django 5.0.2 on 2024-04-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_remove_packagedatemodel_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=50)),
                ('nation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.nationmodel')),
            ],
        ),
    ]
