# Generated by Django 5.0.2 on 2024-04-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_maparea'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maparea',
            table='area_table',
        ),
    ]
