# Generated by Django 5.0.2 on 2024-04-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_alter_maparea_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapArea',
        ),
    ]
