# Generated by Django 5.0.2 on 2024-03-04 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTypeModel',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('User_id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='UserImageModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'user_image',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating_value', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('packages_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packagesmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentModel',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('payment_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.paymenttypemodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'user_payment',
            },
        ),
        migrations.CreateModel(
            name='BookingListModel',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(default='Active', max_length=255)),
                ('order_quantity', models.IntegerField()),
                ('packages_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packagesmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userpaymentmodel')),
            ],
            options={
                'db_table': 'booking_list',
            },
        ),
    ]
