# Generated by Django 5.0.2 on 2024-03-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinglistmodel',
            old_name='packages_id',
            new_name='packages',
        ),
        migrations.RenameField(
            model_name='bookinglistmodel',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='bookinglistmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
