# Generated by Django 5.0.2 on 2024-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_packages_id_bookinglistmodel_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='User_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
