# Generated by Django 5.0.2 on 2024-03-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_usermodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
