# Generated by Django 5.0.2 on 2024-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_usermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating_value',
            field=models.IntegerField(),
        ),
    ]
