# Generated by Django 5.0.2 on 2024-03-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_reviewmodel_rating_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='comment',
            field=models.TextField(),
        ),
    ]
