# Generated by Django 5.0.2 on 2024-03-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_reviewmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
