# Generated by Django 5.0.2 on 2024-03-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_reviewmodel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating_value',
            field=models.CharField(max_length=255),
        ),
    ]
