# Generated by Django 5.0.2 on 2024-03-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_reviewmodel_rating_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimagemodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
