# Generated by Django 5.0.2 on 2024-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_user_id_userimagemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentmodel',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
