# Generated by Django 5.0.2 on 2024-03-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_userpaymentmodel_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpaymentmodel',
            old_name='payment_type_id',
            new_name='payment_type',
        ),
        migrations.RenameField(
            model_name='userpaymentmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
