# Generated by Django 5.0.2 on 2024-03-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_rename_payment_type_id_userpaymentmodel_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglistmodel',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
