# Generated by Django 5.0.2 on 2024-03-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_bookinglistmodel_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentmodel',
            name='package_date',
            field=models.DateField(null=True),
        ),
    ]
