# Generated by Django 5.0.2 on 2024-03-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_bookinglistmodel_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.AlterField(
            model_name='userpaymentmodel',
            name='package_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
