# Generated by Django 5.0.2 on 2024-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_payment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
