# Generated by Django 5.0.2 on 2024-03-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_payment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
