# Generated by Django 5.0.2 on 2024-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_payment_package_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
