# Generated by Django 5.0.2 on 2024-03-31 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_reviewmodel_review_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='packages_id',
            new_name='packages',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
