# Generated by Django 5.0.2 on 2024-04-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_rename_packages_id_reviewmodel_packages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentmodel',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='userpaymentmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookingListModel',
        ),
        migrations.DeleteModel(
            name='PaymentTypeModel',
        ),
        migrations.DeleteModel(
            name='UserPaymentModel',
        ),
    ]
