# Generated by Django 5.0.2 on 2024-04-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_remove_userpaymentmodel_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='members',
            field=models.IntegerField(null=True),
        ),
    ]
