# Generated by Django 5.0.2 on 2024-04-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_delete_maparea'),
        ('userapp', '0022_payment_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=50)),
                ('nation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.nationmodel')),
            ],
            options={
                'db_table': 'area_table',
            },
        ),
    ]
