# Generated by Django 5.0.2 on 2024-04-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_maparea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maparea',
            name='nation_id',
            field=models.IntegerField(),
        ),
    ]
