# Generated by Django 5.0.2 on 2024-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_alter_maparea_nation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
